# Generated by Django 5.0.6 on 2024-07-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('alkhogol_preferens', models.CharField(max_length=250)),
                ('other_important_information', models.TextField(blank=True, null=True)),
                ('second_day', models.CharField(max_length=60)),
                ('sauna', models.CharField(max_length=60)),
                ('beer_preferens', models.CharField(max_length=250)),
                ('other_information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
